### ISSUE TITLE
Broken enchanted books

### ISSUE THREAD

**Issue by TheLemzz** [HimmelKreis4865/JavaGen#4]
![image](https://github.com/HimmelKreis4865/JavaGen/assets/75723466/c02bc3e7-3e2c-402f-816e-895fd6b57c76)

All enchanted books are broken :(

**Comment by HimmelKreis4865** [comment]
Define "All", these enchants are all possible because sometimes, books are enchanted at level 30 (in the enchanting table).
For the most cases, a random enchant with a random level will be picked, so its luck based. Do you feel like enchants are unbalanced op?
Or what do you mean by broken?

**Comment by TheLemzz** [comment]
By "broken" I mean that enchantments are applied to default books, not enchanted ones, so they cannot be applied on anvils (third-party plugin)

**Comment by HimmelKreis4865** [comment]
oh yeah forget about that, thanks

**Comment by HimmelKreis4865** [comment]
good, should now be fixed, please test it if it works for anvils now

**Comment by TheLemzz** [comment]
fixed
