### ISSUE TITLE
No serializer registered for pocketmine\block\UnknownBlock with type ID 10349

### ISSUE THREAD

**Issue by TheLemzz** [HimmelKreis4865/JavaGen#5]
Thread: Main
Error: No serializer registered for pocketmine\block\UnknownBlock with type ID 10349
File: pmsrc/src/data/bedrock/block/convert/BlockObjectToStateSerializer
Line: 257
Type: pocketmine\data\bedrock\block\BlockStateSerializeException
Backtrace:
#0 pmsrc/src/data/bedrock/block/convert/BlockObjectToStateSerializer(215): pocketmine\data\bedrock\block\convert\BlockObjectToStateSerializer->serializeBlock(object pocketmine\block\UnknownBlock#73962)
#1 pmsrc/src/world/format/io/leveldb/LevelDB(228): pocketmine\data\bedrock\block\convert\BlockObjectToStateSerializer->serialize(int 21195322)
#2 pmsrc/src/world/format/io/leveldb/LevelDB(761): pocketmine\world\format\io\leveldb\LevelDB->serializeBlockPalette(object pocketmine\utils\BinaryStream#75192, object pocketmine\world\format\PalettedBlockArray#182456)
#3 pmsrc/src/world/World(1440): pocketmine\world\format\io\leveldb\LevelDB->saveChunk(int 11, int 0, object pocketmine\world\format\io\ChunkData#74124, int -1)
#4 pmsrc/src/world/World(1422): pocketmine\world\World->saveChunks()
#5 pmsrc/src/world/WorldManager(397): pocketmine\world\World->save(false)
#6 pmsrc/src/world/WorldManager(359): pocketmine\world\WorldManager->doAutoSave()
#7 pmsrc/src/Server(1811): pocketmine\world\WorldManager->tick(int 6000)
#8 pmsrc/src/Server(1693): pocketmine\Server->tick()
#9 pmsrc/src/Server(1066): pocketmine\Server->tickProcessor()
#10 pmsrc/src/PocketMine(350): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[20] /root/PocketMine-MP/, string[28] /root/PocketMine-MP/plugins/)
#11 pmsrc/src/PocketMine(373): pocketmine\server()

Installed plugins: DummyItemsBlocks.

**Comment by TheLemzz** [comment]
Maybe it's because I'm using a plugin that registers the spawner block on its own 🤔

**Comment by HimmelKreis4865** [comment]
yeah most likely, though I don't understand how the error can happen, can you maybe send me the plugin if thats possible?

**Comment by TheLemzz** [comment]
My plugin for the spawner just registers the spawner block and changes it a bit so that it can be used to spawn mobs. If this information doesn't help, I can send this plugin via discord

**Comment by TheLemzz** [comment]
I've figured it out, most likely my plugin registers a spawner with a different TypeId, which breaks the generation. It would probably be better if blocks were defined by names rather than by typed I think
