### ISSUE TITLE
Broken generation | all grass block dissappears

### ISSUE THREAD

**Issue by TheLemzz** [HimmelKreis4865/JavaGen#7]
![image](https://github.com/HimmelKreis4865/JavaGen/assets/75723466/23b8ae34-5f7c-4519-9c32-fae58ad33285)
![image](https://github.com/HimmelKreis4865/JavaGen/assets/75723466/1f6efc82-e116-401e-87ea-aecd03191414)

Something very weird.. 
Java world seed: 1408655314417393878
coordinates: -8881 3520

**Comment by TheLemzz** [comment]
Mayy it cause by a high waiting time for the chunk to load...

**Comment by TheLemzz** [comment]
in the screenshot, the dirt line is those places where the grass block is missing
![image](https://github.com/HimmelKreis4865/JavaGen/assets/75723466/f4d30966-8d0f-4192-9006-2fcfd304f849)

**Comment by TheLemzz** [comment]
I think some block was not recognized by the plugin and was replaced with air...

**Comment by HimmelKreis4865** [comment]
> Something very weird.. Java world seed: 1408655314417393878 coordinates: -8881 3520
Are these data correct? tried it in 1.20.4 and I got a different biome there

**Comment by TheLemzz** [comment]
Correct, seed from /seed in Java server and coordinates from pocketmine server

**Comment by HimmelKreis4865** [comment]
can you check yourself what block should be there in reality? I cant reproduce this

**Comment by HimmelKreis4865** [comment]
but all the blocks that are not in pocketmine are also not placed in the generator, thats what I can say

**Comment by HimmelKreis4865** [comment]
so this happens for grass blocks? I dont have this problem tbh

**Comment by TheLemzz** [comment]
I have removed all plugins except DummyItemsBlocks and JavaGen, but the problem is still relevant. There are no third-party plugins on the Java server.

**Comment by HimmelKreis4865** [comment]
try disabling dummyitemblocks one time please

**Comment by TheLemzz** [comment]
Nothing changed

**Comment by TheLemzz** [comment]
![image](https://github.com/HimmelKreis4865/JavaGen/assets/75723466/18ca0885-432b-4946-b921-367d7cf2abc7)
server freezing after 10% of pregeneration of spawn

**Comment by TheLemzz** [comment]
This error is only when generating chunks, the grass blocks themselves do not disappear after the restart.

**Comment by HimmelKreis4865** [comment]
what version of minecraft bedrock are you playing on?

**Comment by TheLemzz** [comment]
> what version of minecraft bedrock are you playing on?

1.20.60

**Comment by HimmelKreis4865** [comment]
Yeah in 1.20.70 minecraft:grass was renamed to minecraft:grass_block, you need 1.20.70

**Comment by TheLemzz** [comment]
bruhh, I will try it now

**Comment by TheLemzz** [comment]
It works, thanks
